CREATE TABLE ARTICLE(
ARTICLE_ID	NUMBER,
GROUP_ID    NUMBER,
SEQUENCE_NO CHAR(16),
POSTING_DATE    DATE,
READ_COUNT	NUMBER,
WRITER_NAME	VARCHAR2(20),
PASSWORD    VARCHAR2(20),
TITLE	VARCHAR2(100),
CONTENT	VARCHAR2(1024),
CONSTRAINT ARTICLE_PK PRIMARY KEY(ARTICLE_ID)
);

CREATE SEQUENCE SEQ_ARTICLE_ID_ARTICLE;
CREATE SEQUENCE SEQ_GROUP_ID_ARTICLE;

select * from user_sequences;

UPDATE article set READ_COUNT=READ_COUNT+1 where ARTICLE_ID=2;